### ISSUE TITLE
[Bug] Object URLs never cleared

### ISSUE THREAD

**Issue by rauenzi** [TheGreenPig/Apate#1]
There are many calls to `URL.createObjectURL()` but no calls to `URL.revokeObjectURL()` which leads to a memory leak. As per MDN:

> Each time you call `createObjectURL()`, a new object URL is created, even if you've already created one for the same object. Each of these must be released by calling `URL.revokeObjectURL()` when you no longer need them.

**Comment by TheGreenPig** [comment]
I was't quite sure where to close them again, but I did this now (version `1.0.6`).
