### ISSUE TITLE
Typo and better descriptions

### ISSUE THREAD

**Issue by 0RadicalLarry0** [TheGreenPig/Apate#10]
Found a typo and thought I should give input on the way some settings are described.

Typo:
![Screenshot_10](https://user-images.githubusercontent.com/54878890/131457279-cae497c5-57aa-44eb-9a5d-f4eef3d811d2.png)

Descriptions:
![Screenshot_11](https://user-images.githubusercontent.com/54878890/131457323-d1bb672a-d3a6-4057-82eb-668214019c10.png)
This could be described better, maybe something like, "Choose whether or not Apate animations are displayed."

![Screenshot_12](https://user-images.githubusercontent.com/54878890/131457799-12776a6a-96e1-472a-9e37-1b14d33b18ab.png)
A bit messy to read as is, could instead be, "If encryption is turned on, all messages will be encrypted with the password defined below. Only people with the exact password you input can see your messages."

![Screenshot_13](https://user-images.githubusercontent.com/54878890/131458980-e1eaafe8-fba1-4649-9816-072e88a57bcf.png)
Some unnecessary words used, I would just simplify it, "If encryption is turned off this field will be ignored."

![Screenshot_14](https://user-images.githubusercontent.com/54878890/131460613-91f91a8d-0377-4510-82bb-7dea2c27c0c2.png)
A little too detailed of a description, try something along the lines of, "All text after the *encrypted message* will be invalid. Enabling this option will delete all invalid text when attempting to send."

![Screenshot_15](https://user-images.githubusercontent.com/54878890/131462556-c12d5310-5894-43ee-a4bb-b79244b89cfd.png)
I feel like this doesn't accurately describe this shortcut, I would use, "Enables the key combination CTRL+Enter to send your message with encryption."

![Screenshot_16](https://user-images.githubusercontent.com/54878890/131463928-3dbf1997-0db0-4ca2-812d-d7ceff0696ba.png)
Accurate but too descriptive, simplify it, "Removes the black background of encrypted messages."

![Screenshot_17](https://user-images.githubusercontent.com/54878890/131464246-f7b89572-b888-4627-a743-7c3a4f41b705.png)
The way this is currently described makes it sound like your IP might be accidentally grabbed by the plugin itself. I would change it to, "Links to images will be displayed. WARNING: Any image links hosted on an IP logger will be displayed as well, this can reveal your IP address."

**Comment by 0RadicalLarry0** [comment]
I'm sure there are better ways to describe everything but I thought I would give some feedback since the current descriptions imo could be better.

**Comment by TheGreenPig** [comment]
I added the suggested changes in `1.0.6`
