### ISSUE TITLE
Fix [loading hidden message...] on encrypted messages

### ISSUE THREAD

**Issue by 0RadicalLarry0** [TheGreenPig/Apate#11]
Even if you can't see an encrypted message you can still see the [loading hidden message...]

https://user-images.githubusercontent.com/54878890/131469212-65f7efd6-65c5-4801-b21a-bbe96cf8d265.mp4

**Comment by TheGreenPig** [comment]
Right now the code works by going through every message and marking those with a specific indicator character as hidden messages and then applies the "loading" class... loading essentially means, apate still has to try decrypting the message.  If the password is incorrect, the loading message just dissappears.

So basically I have two options: 
1. There is no loading message all together.
2. The loading message dissappears as soon as it notices you don't have the correct password (this is how it is right now).

**Comment by 0RadicalLarry0** [comment]
Maybe add an additional check before applying said "loading" class where it silently checks if the passwords match? Then if they do add the loading class. (I'm not too sure how js works but I'd imagine this is possible?)

Not sure how else to go about it, I'm only bringing this up as an issue since some people might still be bothered by this. (one of those people being me lol)

**Comment by TheGreenPig** [comment]
Well "checking if the passwords match" essentially IS the loading phase. I could add an option to turn the loading message off I guess...

**Comment by 0RadicalLarry0** [comment]
I suppose that could work.. Although it loads fast enough for the indicator to not be necessary at all, idk.

I don't want to keep bothering you about it so I guess it's whatever. I'm just nitpicking at this point anyways.

**Comment by TheGreenPig** [comment]
I added a feature to disable the loading messages in `1.0.6`.
