### ISSUE TITLE
Most recent update breaks the plugin

### ISSUE THREAD

**Issue by gurrrrrrett3** [TheGreenPig/Apate#13]
After installing the newest version, Encrypted messages no longer show up.
![image](https://user-images.githubusercontent.com/61361654/131554278-429442ff-108e-4f28-a6e0-29703cfb4d14.png)

It just says _Loading hidden message..._ and then the message box disappears.

**Comment by TheGreenPig** [comment]
Are you sure you have the correct Password in your password list? If the message box just disappears, you don't have the correct password anywhere.
