### ISSUE TITLE
Images are directly loaded

### ISSUE THREAD

**Issue by FrostBird347** [TheGreenPig/Apate#2]
This allows users to obtain IP addresses by sending image links hosted on IP loggers.
Using an image proxy for the decoded image link would fix this issue, however I can't see an easy way of doing it with discord's own image proxy.

**Comment by TheGreenPig** [comment]
I am aware of this issue, but to be completely honest, I don't know how to fix this. Maybe I should disable the show image option all together, at least until I, or someone else, has found a fix. So if somebody knows how to fix this, please send a merge request or share your thoughts here.

**Comment by FrostBird347** [comment]
At the very least you should disable it by default and show a warning next to the option.

**Comment by TheGreenPig** [comment]
I gave the setting into an "Experimental" Group and made it false by default. Hope someone can find a fix for this...

**Comment by TheGreenPig** [comment]
All images are now loaded through the [images.weserv.nl](https://images.weserv.nl/) proxy. I moved this setting back out of the experimental tab as it should be secure now.
