### ISSUE TITLE
[Suggestion] Per-Message password

### ISSUE THREAD

**Issue by Variapolis** [TheGreenPig/Apate#20]
It would be great to be able to choose a password to use from a dropdown, possibly by right-clicking on the key when posting messages. Sometimes, I would like to encrypt my message, but a lot of the time I want it to be publicly visible or use a different password without going into settings.

How it would look:
1. Create/Add a password
2. Type in a message
3. Special-click on key
4. Choose a password to use OR NONE
5. Post with special message password set or public.

**Comment by TheGreenPig** [comment]
Implemented this feature just now in version `1.2.4` (Right-click the Key)
