### ISSUE TITLE
not showing the hidden messages

### ISSUE THREAD

**Issue by programing-monkey** [TheGreenPig/Apate#23]
I can send messages which have a hidden part, just not see them.
there are no error messages in the console, I am on the newest version of better discord and Apate, and have no other enabled plugins.
![image](https://user-images.githubusercontent.com/36543893/132421051-ed09f006-032d-4a16-ae3c-abab107c6c4b.png)
![image](https://user-images.githubusercontent.com/36543893/132421064-87e9edee-67dc-4953-9399-8e0f0fcc7578.png)

**Comment by TheGreenPig** [comment]
This might have to do with the fact that the cover message is only one word. Try sending a message with a cover message that has at least two words. I will add a warning for this in the future.

**Comment by programing-monkey** [comment]
it worked thanks!
