### ISSUE TITLE
Cant send hidden message

### ISSUE THREAD

**Issue by Caelanj** [TheGreenPig/Apate#28]
I'm not sure if I'm just being really stupid or what, but clicking the key and doing shift+enter simply
don't do anything. I have the newest version, I have the Zeres library thing installed, and I even disabled all other plugins.
![ezgif-2-5a6839bc05aa](https://user-images.githubusercontent.com/37782194/133190592-143c4cd8-5cd6-4871-9b09-dfc96b8eedeb.gif)

**Comment by TheFlagen430297** [comment]
![image](https://user-images.githubusercontent.com/60035052/134107710-a2070363-4659-4315-be3a-dcf2b16d4085.png)
Did you also click Control?

**Comment by TheGreenPig** [comment]
The issue was most likely because the cover Message was only one word. This should be fixed by now though and one-word cover message should work.
