### ISSUE TITLE
Add user password protection for messages

### ISSUE THREAD

**Issue by 0RadicalLarry0** [TheGreenPig/Apate#3]
Add the ability to set a password for your messages in the settings so only people with that same password can access your messages.

Not sure if it's possible but I thought it would be a neat idea so you can talk to specific people sharing the same message password.

E.g. You set your password to "1234" in the settings and everyone with that same password can access your messages encrypted with "1234". But if you don't have that exact password the message can't be displayed.

I feel like this would add some privacy for groups of friends that want to talk to each other without some random dude with the plugin being able to view their messages.

**Comment by 0RadicalLarry0** [comment]
I was looking around and the functionality to encrypt messages with a user defined password is built into stegcloak.

There's already another plugin that has this feature for powercord although I don't know if it automatically decrypts messages like this plugin.

Looks like you have some competition!

**Comment by TheGreenPig** [comment]
I added this Feature just now in version `1.0.4`. Download it and try it out... even if the Encryption is turned off in the settings, the plugin still does some basic encryption by generating a random zero-width string that gets sent with the cover message. It is not by any means secure, but it prevents people from simply copy-pasting the messages into the stegcloak website!
