### ISSUE TITLE
DM Encryption Support

### ISSUE THREAD

**Issue by AlecHCodes** [TheGreenPig/Apate#32]
Hello, this isn't necessarily an issue, just a feature suggestion.

The Key Bind/Key GUI to enable hidden encrypted messages via Apate works/shows up, as expected, in actual servers:

![image](https://user-images.githubusercontent.com/87393142/134790950-19bbdb69-3777-40f2-a88d-e32b86ef1458.png)

But not Direct Messages/Group DMs:

![image](https://user-images.githubusercontent.com/87393142/134791053-3aa563bb-ccd2-4740-9a93-f13dee57a288.png)

Is there any specific reason why this is the case? If possible, could you implement DM functionality in the future?

**Comment by NutNutty64** [comment]
newest update seems to have caused this, dm support **is** a thing just wait for a fix

**Comment by TheGreenPig** [comment]
Should be fixed now in `1.3.3`. Thanks for letting me know.
