### ISSUE TITLE
Question / Suggestion

### ISSUE THREAD

**Issue by RobinRMC** [TheGreenPig/Apate#39]
When the plugin got released, there wasn't a limit on how many passwords you could configure. Why have you decided to add a limit, and can it be removed or increased?

**Comment by TheGreenPig** [comment]
I mainly put in the limit out of 3 reasons:

1. Not necessary. Realistically nobody is going to need more than 30 passwords so I didn't view it as necessary. Also the list gets very long an unorganized very fast. 

2. Performance. Apate doesn't know which password was used when trying to decrypt so every password has to be checked. I tried to optimize it by giving passwords that are used often more priority, but if you have say 100 passwords and I send you a message encrypted with a password you don't have, your PC has do try the decryption process 100 times per message. That takes a lot of time.

3. Bad attempts at dictionary attacks. This is probably a very insignificant reason, but still, I didn't want people to have like a list of the most used passwords, just so they can read more messages.

If you can give me a good reason why I should increase/take away the limit, please let me know!

**Comment by RobinRMC** [comment]
Well.. I think that it's better to increase the limit to 50. That way, people can use different passwords for every chat and they don't stumble across the limit. I personally think that 30 is alright, but it can also limit the possibilities. Therefore, I think that 50 is a choice.
