### ISSUE TITLE
apate nonfunctional on my machine

### ISSUE THREAD

**Issue by ghost** [TheGreenPig/Apate#40]
none of the hotkeys work for me, my about page doesnt have a hidden message, there's no key button, etc. thinking there was a potential conflict, i removed every plugin except apate from my plugins folder and disabled my themes, apate then failed to start so i put everything back. i went to the discord and looked through the issues, someone had a conflict with copier, was found through console. checked console, and apparently there was an uncaught reference error to cryptico. fyi, i got the plugin from plugin repo

**Comment by hackaholic5069** [comment]
![image](https://user-images.githubusercontent.com/37553921/138373836-e1d6d3b8-b0ca-4100-82f1-2c3121ca6e8b.png)
