### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by OG-Jons** [TheGreenPig/Apate#49]
There's a typo at Line 1336.

[https://github.com/TheGreenPig/Apate/blob/main/Apate.plugin.js#L1336](https://github.com/TheGreenPig/Apate/blob/main/Apate.plugin.js#L1336
)

Change `Synatax` to `Syntax` 

I have forked and fixed it, but I think it would be too big for a PR, which you had rejected before, for a typo.

**Comment by TheGreenPig** [comment]
Thanks for the Info, I fixed it in `1.4.8`!
