### ISSUE TITLE
Error when using _ instead of * when creating italic text

### ISSUE THREAD

**Issue by Shandeika** [TheGreenPig/Apate#5]
I used this construction:
`_test_`
And I got an error:
`Something went wrong... Mark your hidden message as italic!`
![logo](https://i.imgur.com/GfZwxb8.png)

The design of this type does not cause errors:
`*test*`

**Comment by TheGreenPig** [comment]
This is an incorrect Error message of mine, i might have to rephrase that. The plugin extracts the hidden message by checking for * and not actually for italic text. **Please use only `*` to set the hidden message.**
