### ISSUE TITLE
Most recent update (today) broke plugin.

### ISSUE THREAD

**Issue by DonJTru** [TheGreenPig/Apate#50]
As the title states, I got a banner saying there was an update, I do the update and now it will not work, it also broke another plugin of mine (edit users) that was changing the color of specific user's messages to a custom one causing it all to become gray.

**Comment by TheGreenPig** [comment]
How exactly is it broken? It works fine for me... I updated some colors of the plugin to fit more themes, but it shouldn't change any colors of your plugin.
