### ISSUE TITLE
copy button for passwords doesnt work, and end to end seems fucked up

### ISSUE THREAD

**Issue by ZellsAlpha** [TheGreenPig/Apate#51]

**Comment by TheGreenPig** [comment]
Please actually explain your issue instead of just writing `end to end seems fucked up`

**Comment by ZellsAlpha** [comment]
it was just functioning weirdly cause the other person wouldn't get the request but i think it was just discord acting up

I'm having an issue with the hidden about me option? it doesn't seem to do anything, is there a specific way to use it or is it not working atm? my friends couldnt see anything on my about me page :(
