### ISSUE TITLE
Apate causes duplicate messages?

### ISSUE THREAD

**Issue by VDKA-Deado** [TheGreenPig/Apate#53]
An odd issue I'm dealing with: Whenever I load Discord (including re-loading via CTRL+R), my messages always get sent twice and I can't see other people's encrypted segments of messages til I delete and reinstall Apate to my Discord client... Any ideas on what could be causing this? I do have 60 plugins total so there's a chance that another plugin _may_ be causing the issue, but I don't know for certain.

**Comment by TheGreenPig** [comment]
Sorry I can't really help you with that... I'm not aware of any plugins that interfere with Apate. Make sure you have a good internet connection and maybe try different combinations of plugins with apate so you can find out if there really is a plugin causing issues.
