### ISSUE TITLE
Editing message send non-encrypted message

### ISSUE THREAD

**Issue by koliwbr** [TheGreenPig/Apate#54]
If I send ex. 
> Hi! \*I<3u\*

then press Ctrl+Enter to send encrypted message and press ArrowUp, change text to
> Hi Marta \*I<3u\*

and press enter (or ctrl+enter) sends 
![image](https://user-images.githubusercontent.com/61465776/149391145-bab61925-3f42-4791-b5fb-a6e7aecf8fab.png)
not
![image](https://user-images.githubusercontent.com/61465776/149391278-2bda0c4d-92f9-4567-a0b2-128083050e61.png)

**Comment by TheGreenPig** [comment]
That's just the way the editing works with this plugin (https://github.com/TheGreenPig/Apate/blob/main/Assets/Tutorials/README.md#editing-messages)
> To edit a message, click the edit button, change what you want and then Click the Key again!. If you just press Enter, your message will be revealed instead of hidden.
 
 you should be able to press Ctrl+Enter to encrypt it though.

**Comment by koliwbr** [comment]
Ctrl+Enter not work

**Comment by TheGreenPig** [comment]
Are you on the newest version and have the shortcut turned on in the settings?

**Comment by Plushhh** [comment]
Yes I do. It doesn't work.
