### ISSUE TITLE
Version 1.4.6 crashes BetterDiscord 1.4.0

### ISSUE THREAD

**Issue by JavkhlanK** [TheGreenPig/Apate#57]
I saw Apate having an update in some toolbar, and after installing it & reloading Discord, the entire app stopped working. I tracked the issue down to Apate by backing the old plugins folder up & enabling just these plugins (not Apate as with it the app's crashing):
![image](https://user-images.githubusercontent.com/40118124/151707204-89ab8d57-a592-4804-8ab6-4f13c70fce31.png)

And for the "error message", this is the most I could get:
![image](https://user-images.githubusercontent.com/40118124/151707252-5090f8d3-ee8d-4127-aaa6-3c4b1702d69b.png)

**Comment by TheGreenPig** [comment]
Yeah sorry that was a really stupid mistake on my end. Should be now, download from source please.
