### ISSUE TITLE
only seems to work in DM

### ISSUE THREAD

**Issue by AcesGamingUK** [TheGreenPig/Apate#63]
i can only seem to get this to work on DM,
is there something im missing?
both the `Key` and `CTRL+Enter` work in DM
both nothing works in any discord channel
![Discord_FzOoVGFY1E](https://user-images.githubusercontent.com/16180389/162594500-e17b2291-83fe-475d-b547-23ac3ae27a53.gif)

**Comment by TheGreenPig** [comment]
Should be fixed in `1.5.7`
