### ISSUE TITLE
Better Discord Version

### ISSUE THREAD

**Issue by FSATAK** [TheGreenPig/Apate#8]
The betterdiscord version has to be 1.2.1. It doesn't work on anything below that. I am writing here just to inform you of that.

**Comment by TheGreenPig** [comment]
Really? Interesting... do you know why? Making the plugin work for older versions of betterdiscord isn't my main priority at the moment but it's still good to know...

**Comment by FSATAK** [comment]
no idea. me and a friend were trying it out and he was able to read the messages but not send them. so we compared everything about discord down to the plugins we each had and noticed he had 1.2.0 after he had updated it worked fine.

the only thing we found was this in the console- https://cdn.discordapp.com/attachments/786379578758266890/881942489529983006/unknown.png

I also enjoy using the plugin. Thanks for making it.
