### ISSUE TITLE
Corrupted message when including an emoji

### ISSUE THREAD

**Issue by fabJunior** [TheGreenPig/Apate#9]
## When the second word of the cover message is an emoji, on certain occasions the hidden message will break.

For example, if I want to hide the message "done" with the message `Mhhh :shibathink: *done*` the result is as follows:
![Discord_jPqer38d36](https://user-images.githubusercontent.com/16782977/131415872-182ec303-fe7e-4f36-9d2a-8c97638bd5e8.jpg)

I also tried to hide the message "ok" with `so :AquaInspect: mhh *ok*` and the result:
![Discord_deOXYaUcJz](https://user-images.githubusercontent.com/16782977/131415949-3cfa4eb5-93f2-46a3-b298-65d84e292623.jpg)

With a longer message `Alright :ablobnod: will it work *or will it fail?*`:
![Discord_kNOmBU3qAB](https://user-images.githubusercontent.com/16782977/131416021-8780d838-2c74-4077-af0d-95a1ee4073f9.jpg)

---

Usually, the last character is altered/deleted (or last few characters) and in some occasions the whole hidden message is reduced to nothing, as if no message was hidden. However, sometimes, nothing bad happens, so it's a bit of a gamble.

What I've understood is that when I type a message, like `Mhhh :shibathink: *done*`, the text that the reveal worker will get is `Mhhh ` (with a trailing space) instead of `Mhhh :shibathink:` and that's what's breaking some messages.

In fact, it seems to work fine when I make the revealWorker get the innerHTML of the message instead of the textContent in the `addHiddenMessageBanners` method.

```js
// const textContent = messageContainer.querySelector(
// 	`div[class*="contents-"][role="document"] > div[class*="markup-"][class*="messageContent-"]`
// ).textContent;

const textContent = messageContainer.querySelector(
	`div[class*="contents-"][role="document"] > div[class*="markup-"][class*="messageContent-"]`
).innerHTML;
```

---

After fiddling a bit with the code, I came up with this possibly more elegant fix in `addHiddenMessageBanners` where the `const textContent` is initialized:

```js
const domMessage = messageContainer.querySelector(
	`div[class*="contents-"][role="document"] > div[class*="markup-"][class*="messageContent-"]`
).cloneNode(true);

const messageEmojis = domMessage.querySelectorAll(`span[class*="emojiContainer-"]`);

for (let emoji of messageEmojis) {
	emoji.innerHTML = emoji.children[0].alt;
}

const textContent = domMessage.textContent;
```

The result is `textContent` having the proper `:emoji:` text:

![Discord_G5LAL6V7mM](https://user-images.githubusercontent.com/16782977/131420566-45b9574d-304f-4680-8799-165e816370e8.jpg)

**Comment by TheGreenPig** [comment]
I implemented your suggested fix, I hope it works now.
